name: Replicate bans

on:
  # manually
  workflow_dispatch:
  # schedule:
    # every two minutes
    # - cron: "*/2 * * * *"

jobs:
  pull_stats:
    runs-on: ubuntu-latest

    steps:
      - name: ⚙️ Install jq
        run: sudo apt-get install -y jq
      - uses: actions/checkout@v2
        with:
          ref: main

      - name: 🗄 Fetch Objkt.com bans
        run: |
          curl https://back.objkt.com/api/v1/bans.json | jq ".banned" > objktcom.json
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: ✨ Update bans
